# Source page enums:
HOME = "HOME"
LOGIN = "LOGIN"
PROFILE = "PROFILE"
CREATE_POST = "CREATE_POST"
CREATE_EVENT = "CREATE_EVENT"

DEFAULT = "DEFAULT"

TOOLBAR_LOGIN = "TOOLBAR_LOGIN"
TOOLBAR_HOME = "TOOLBAR_HOME"
TOOLBAR_LOGOUT = "TOOLBAR_LOGOUT"
TOOLBAR_PROFILE = "TOOLBAR_PROFILE"

CREATE_BASIC_ACCOUNT_FINISH = "CREATE_BASIC_ACCOUNT_FINISH"
SETUP_ACCOUNT_FINISH = "SETUP_ACCOUNT_FINISH"

EDIT_INTERESTS = "EDIT_INTERESTS"
EDIT_PROFILE_PICTURE = "EDIT_PROFILE_PICTURE"
EDIT_PROFESSIONS = "EDIT_PROFESSIONS"
EDIT_BACKGROUND = "EDIT_BACKGROUND"

URL_MAP = {HOME: "/",
		   LOGIN:"/login/",
		   CREATE_POST: "/create/post/choose/",
		   CREATE_EVENT: "/create/event/",
		   CREATE_BASIC_ACCOUNT_FINISH: "/account/create/finish/",
		   SETUP_ACCOUNT_FINISH: "/account/create/finish/",
		   EDIT_INTERESTS: "/account/edit/interests/",
		   EDIT_PROFESSIONS: "/account/edit/professions/",
		   EDIT_PROFILE_PICTURE: "/account/edit/picture/",
		   EDIT_BACKGROUND: "/account/edit/background/"
		   }

# format is {currentPage: {source1: dest1, source2:dest2, source3: {pagekey1: dest3-1, pagekey2: dest3-2}}}
PAGE_MAP = {DEFAULT: HOME,
			EDIT_INTERESTS: {PROFILE: {DEFAULT: PROFILE},
							 CREATE_BASIC_ACCOUNT_FINISH: {DEFAULT: EDIT_PROFESSIONS}},
			LOGIN: {HOME: {DEFAULT: HOME,
						   HOME: HOME,
						   CREATE_EVENT: CREATE_EVENT,
						   CREATE_POST: CREATE_POST}}}
