# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 16:49
from __future__ import unicode_literals

import AgencyApp.python.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.CharField(max_length=10)),
                ('poster', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=5000, null=True)),
                ('postPicturePath', models.CharField(blank=True, default=None, max_length=5000, null=True)),
                ('postPicture', models.ImageField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media//', location='/Users/MattGray/Projects/Agency/Agency/media/'), upload_to=AgencyApp.python.models.image_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.CharField(max_length=10)),
                ('poster', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=5000, null=True)),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
                ('eventPicturePath', models.CharField(blank=True, default=None, max_length=5000, null=True)),
                ('eventPicture', models.ImageField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media//', location='/Users/MattGray/Projects/Agency/Agency/media/'), upload_to=AgencyApp.python.models.image_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('professionName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('setupComplete', models.BooleanField(default=False)),
                ('workInterest', models.BooleanField(default=False)),
                ('crewInterest', models.BooleanField(default=False)),
                ('collaborationInterest', models.BooleanField(default=False)),
                ('profilePicture', models.ImageField(default=None, storage=django.core.files.storage.FileSystemStorage(base_url='/media//', location='/Users/MattGray/Projects/Agency/Agency/media/'), upload_to=AgencyApp.python.models.image_directory_path)),
                ('reelLink', models.CharField(default='', max_length=500)),
                ('imdbLink', models.CharField(default='', max_length=500)),
                ('bio', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationPost',
            fields=[
                ('abstractpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AgencyApp.AbstractPost')),
                ('profession', models.CharField(max_length=200)),
            ],
            bases=('AgencyApp.abstractpost',),
        ),
        migrations.CreateModel(
            name='ProjectPost2',
            fields=[
                ('abstractpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AgencyApp.AbstractPost')),
                ('status', models.CharField(max_length=50)),
            ],
            bases=('AgencyApp.abstractpost',),
        ),
        migrations.CreateModel(
            name='WorkPost',
            fields=[
                ('abstractpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AgencyApp.AbstractPost')),
                ('projectPostID', models.CharField(max_length=10)),
                ('profession', models.CharField(max_length=200)),
                ('paid', models.BooleanField(default=False)),
            ],
            bases=('AgencyApp.abstractpost',),
        ),
    ]
