# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0002_auto_20170511_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
