# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0003_auto_20170511_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('abstractpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AgencyApp.AbstractPost')),
                ('location', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            bases=('AgencyApp.abstractpost',),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
