# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0003_auto_20170326_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='profileName',
            new_name='username',
        ),
    ]
