# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0004_auto_20170513_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
