# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0004_auto_20170327_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='setupComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
