# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0005_auto_20170327_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='collaborationInterest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='crewInterest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='workInterest',
            field=models.BooleanField(default=False),
        ),
    ]
