# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0006_auto_20170327_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('actor', models.BooleanField(default=False)),
                ('director', models.BooleanField(default=False)),
                ('writer', models.BooleanField(default=False)),
                ('cinematographer', models.BooleanField(default=False)),
                ('other', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
