# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0006_auto_20170513_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingPost',
            fields=[
                ('abstractpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AgencyApp.AbstractPost')),
                ('paid', models.BooleanField(default=False)),
            ],
            bases=('AgencyApp.abstractpost',),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
