# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0007_auto_20170514_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
