# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0007_professions'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='bio',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='imdbLink',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profilePicture',
            field=models.FileField(default=None, upload_to=b''),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='reelLink',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
