# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0008_postfollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActorDescriptionBooleanAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('attributeName', models.CharField(max_length=200)),
                ('attributeValue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ActorDescriptionStringAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('attributeName', models.CharField(max_length=200)),
                ('attributeValue', models.CharField(max_length=200)),
            ],
        ),
    ]
