# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0008_auto_20170327_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='bio',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='imdbLink',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profilePicture',
            field=models.FileField(default='', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='reelLink',
            field=models.CharField(default='', max_length=500),
        ),
    ]
