# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0009_actor_actordescriptionbooleanattribute_actordescriptionstringattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingpost',
            name='projectID',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
