# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0010_auto_20170327_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='bio',
            field=models.CharField(default='blah', max_length=1000),
        ),
    ]
