# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0011_auto_20170527_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='actordescriptionbooleanattribute',
            name='postID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='actordescriptionbooleanattribute',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
