# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0012_auto_20170527_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingpost',
            name='descriptionEnabled',
            field=models.BooleanField(default=False),
        ),
    ]
