# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0013_castingpost_descriptionenabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workpost',
            old_name='projectPostID',
            new_name='projectID',
        ),
        migrations.AddField(
            model_name='castingpost',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='workpost',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
    ]
