# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0014_auto_20170404_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profileImage',
            field=models.ImageField(default=None, upload_to=b''),
        ),
    ]
