# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0014_auto_20170528_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castingpost',
            name='projectID',
        ),
        migrations.RemoveField(
            model_name='workpost',
            name='projectID',
        ),
        migrations.AddField(
            model_name='abstractpost',
            name='projectID',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
