# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0015_auto_20170529_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractpost',
            name='projectID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
