# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0016_auto_20170529_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castingpost',
            name='status',
        ),
        migrations.RemoveField(
            model_name='projectpost',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workpost',
            name='status',
        ),
        migrations.AddField(
            model_name='abstractpost',
            name='status',
            field=models.CharField(blank=True, default='Available', max_length=50, null=True),
        ),
    ]
