# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0018_useraccount_actinginterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='castingInterest',
            field=models.BooleanField(default=False),
        ),
    ]
