# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 06:09
from __future__ import unicode_literals

import AgencyApp.python.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0019_auto_20170404_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profilePicture',
            field=models.ImageField(default=None, storage=django.core.files.storage.FileSystemStorage(base_url='/media//', location='/Users/MattGray/Projects/Agency/Agency/media/'), upload_to=AgencyApp.python.models.image_directory_path),
        ),
    ]
