# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0019_useraccount_castinginterest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborationpost',
            old_name='profession',
            new_name='collaboratorRole',
        ),
    ]
