# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0020_auto_20170404_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='firstName',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='lastName',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
