# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0021_auto_20170407_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professions2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professions', models.CharField(default=b'["Actor", "Acting Coach", "Art Director", "Assistant Director", "Assistant Camera Operator", "Boom Operator", "Camera Operator", "Casting Director", "Choreographer", "Cinematographer", "CG Animator", "Compositor", "Costume Designer", "Concept Artist", "Dancer", "Director", "Editor", "Film Festival Director", "Film Festival Volunteer", "Graphic Designer", "Grip", "Hair Stylist", "Key Grip", "Lighting Technician", "Location Manager", "Makeup Artist", "Marketing", "Music Composer", "Music Supervisor", "Music Editor", "Musician", "Photographer", "Producer", "Production Assistant", "Production Caterer", "Production Coordinator", "Production Designer", "Production Manager", "Prop Master", "Screenwriter", "Script Coordinator/Supervisor", "Set Coordinator", "Set Decorator", "Set Design", "SFX Technician", "SFX Supervisor", "Songwriter", "Sound Editor", "Sound Engineer", "Storyboard Artist", "Stunt Coordinator", "Stunt Artist", "Talent Management", "VFX Arist", "VFX Supervisor", "Voice Artist", "Wardrobe Supervisor"]', editable=False, max_length=500)),
            ],
        ),
    ]
