# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0021_useraccount_actordescriptionenabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('subInterestName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='castingInterest',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='collaborationInterest',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='crewInterest',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='workInterest',
        ),
    ]
