# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0022_auto_20170606_0712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.AddField(
            model_name='profession',
            name='mainInterest',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profession',
            name='subInterest',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
