# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0023_auto_20170411_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
    ]
