# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0023_auto_20170607_0217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profession',
            new_name='Interest',
        ),
    ]
