# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0024_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profession',
            old_name='name',
            new_name='professionName',
        ),
    ]
