# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0024_auto_20170609_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='actingInterest',
        ),
        migrations.AddField(
            model_name='interest',
            name='actingDescriptionEnabled',
            field=models.BooleanField(default=False),
        ),
    ]
