# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0025_auto_20170610_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='mainProfession',
            field=models.CharField(default='', max_length=200),
        ),
    ]
