# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0025_auto_20170411_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='username',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
