# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0026_profession_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='selected',
        ),
    ]
