# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0026_useraccount_mainprofession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractpost',
            name='status',
            field=models.CharField(blank=True, default='Open', max_length=50, null=True),
        ),
    ]
