# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0027_auto_20170616_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.CharField(max_length=10)),
                ('projectID', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, default='Available', max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.CharField(max_length=10)),
                ('projectID', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, default='Open', max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
