# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0027_remove_profession_selected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professions2',
        ),
    ]
