# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0028_delete_professions2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professionName', models.CharField(max_length=100)),
            ],
        ),
    ]
