# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0028_projectjob_projectrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjob',
            name='profession',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrole',
            name='characterDescription',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='characterName',
            field=models.CharField(default='John Wick', max_length=200),
            preserve_default=False,
        ),
    ]
