# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0029_auto_20170619_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='roleType',
            field=models.CharField(blank=True, default='Acting', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectjob',
            name='status',
            field=models.CharField(blank=True, default='Hiring', max_length=50, null=True),
        ),
    ]
