# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0029_masterprofession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professions',
        ),
    ]
