# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0030_auto_20170620_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='shortCharacterDescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
