# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0030_delete_professions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.CharField(max_length=10)),
                ('poster', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='MasterProfession',
        ),
    ]
