# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0031_auto_20170424_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
