# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0032_projectjob_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjob',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
