# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0033_projectjob_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10)),
            ],
        ),
    ]
