# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0034_projectadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectRole',
        ),
        migrations.AddField(
            model_name='castingpost',
            name='ageRange',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='castingpost',
            name='build',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='castingpost',
            name='characterName',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='castingpost',
            name='complexion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='castingpost',
            name='eyeColor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='castingpost',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='castingpost',
            name='hairColor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='castingpost',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='castingpost',
            name='roleType',
            field=models.CharField(blank=True, default='Acting', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='castingpost',
            name='shortCharacterDescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='castingpost',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='castingpost',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
