# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0035_auto_20170702_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingpost',
            name='actorName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
