# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0037_auto_20170702_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castingpost',
            name='weight',
        ),
        migrations.AddField(
            model_name='castingpost',
            name='endDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='castingpost',
            name='hoursPerWeek',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='castingpost',
            name='languages',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='castingpost',
            name='paidAmount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='castingpost',
            name='skills',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='castingpost',
            name='startDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
