# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0038_auto_20170704_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingpost',
            name='characterType',
            field=models.CharField(default='Actor', max_length=100),
        ),
    ]
