# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-25 18:08
from __future__ import unicode_literals

import AgencyApp.python.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0042_auto_20170717_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPostPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempID', models.CharField(max_length=10)),
                ('postPicture', models.ImageField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media//', location='/Users/MattGray/Projects/Agency/Agency/media/'), upload_to=AgencyApp.python.models.image_directory_path)),
            ],
        ),
    ]
