# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-25 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0044_temppostpicture_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workpost',
            old_name='workerName',
            new_name='username',
        ),
        migrations.AddField(
            model_name='workpost',
            name='endDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='workpost',
            name='equipmentDescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workpost',
            name='hoursPerWeek',
            field=models.TextField(blank=True, default='TBD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workpost',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='workpost',
            name='paidDescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workpost',
            name='skills',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='workpost',
            name='startDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='workpost',
            name='workerNeedsEquipment',
            field=models.BooleanField(default=True),
        ),
    ]
