# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0045_auto_20170725_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workpost',
            old_name='username',
            new_name='workerName',
        ),
        migrations.RemoveField(
            model_name='castingpost',
            name='username',
        ),
    ]
