# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0047_auto_20170727_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='projectType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='union',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
