# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0048_auto_20170727_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='admissionInfo',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='endTime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='host',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='startTime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
