# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0051_auto_20170816_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castingpost',
            old_name='complexion',
            new_name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='castingpost',
            name='shortCharacterDescription',
        ),
        migrations.AddField(
            model_name='castingpost',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
