# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0052_auto_20170820_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castingpost',
            old_name='paidDescription',
            new_name='compensationDescription',
        ),
        migrations.RemoveField(
            model_name='castingpost',
            name='paid',
        ),
        migrations.AddField(
            model_name='castingpost',
            name='compensationType',
            field=models.BooleanField(default=False),
        ),
    ]
