# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0054_auto_20170820_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workpost',
            old_name='paidDescription',
            new_name='compensationDescription',
        ),
        migrations.RemoveField(
            model_name='workpost',
            name='paid',
        ),
        migrations.AddField(
            model_name='workpost',
            name='compensationType',
            field=models.CharField(blank=True, default='Unpaid', max_length=200, null=True),
        ),
    ]
