# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0055_auto_20170821_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpost',
            old_name='date',
            new_name='startDate',
        ),
        migrations.RemoveField(
            model_name='workpost',
            name='shortDescription',
        ),
        migrations.AddField(
            model_name='eventpost',
            name='endDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
