# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0057_auto_20170825_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='postparticipant',
            name='privateParticipation',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
