# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-29 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0060_auto_20170829_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postparticipant',
            old_name='label',
            new_name='status',
        ),
    ]
