# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-03 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0062_useraccount_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castingpost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='eventpost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='projectpost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='workpost',
            name='location',
        ),
        migrations.AddField(
            model_name='abstractpost',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
