# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0063_auto_20170903_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractpost',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstractpost',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
