# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 19:40
from __future__ import unicode_literals

import AgencyApp.python.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0065_auto_20170910_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='resume',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(base_url='/media//', location='/Users/MattGray/Projects/Agency/Agency/media/'), upload_to=AgencyApp.python.models.image_directory_path),
        ),
    ]
