# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0066_useraccount_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpost',
            name='length',
        ),
        migrations.AddField(
            model_name='projectpost',
            name='companyName',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='compensationDescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='compensationType',
            field=models.CharField(blank=True, default='Unpaid', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='endDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='productionNotes',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='startDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='union',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
