# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0068_auto_20170918_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='eventType',
            field=models.CharField(blank=True, default='Other', max_length=200, null=True),
        ),
    ]
