# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0069_eventpost_eventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='imdbLink',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
