# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 22:42
from __future__ import unicode_literals

import AgencyApp.python.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0070_auto_20170920_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='resume',
            field=models.FileField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media//', location='/Users/MattGray/Projects/Agency/Agency/media/'), upload_to=AgencyApp.python.models.image_directory_path),
        ),
    ]
