# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0071_auto_20170920_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='mainProfession',
        ),
    ]
