# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0072_remove_useraccount_mainprofession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='actorDescriptionEnabled',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='build',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='ethnicity',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='eyerColor',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='hairColor',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='height',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
