# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0073_auto_20170921_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='eyerColor',
            new_name='eyeColor',
        ),
    ]
