# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0075_auto_20170921_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.CharField(max_length=10)),
                ('poster', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('projectType', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('profession', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('year', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
