# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-28 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0078_auto_20170928_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemediapicture',
            old_name='picture',
            new_name='postPicture',
        ),
    ]
