# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-29 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0079_auto_20170928_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemediapicture',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
