# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0081_profilemediapicture_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEndorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
