# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-09 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0082_profileendorsement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageID', models.CharField(max_length=10)),
                ('sender', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('recipientSeen', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
    ]
