# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-10 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0084_message_senttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversationID', models.CharField(max_length=10)),
                ('user1', models.CharField(max_length=100)),
                ('user2', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='conversationID',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
