# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-11 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0085_auto_20171010_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
