# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-17 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0086_remove_message_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='lastLogin',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
