# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-17 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0087_useraccount_lastlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='lastLogin',
            new_name='lastLogout',
        ),
    ]
