# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-30 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0088_auto_20171017_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='applicationMessage',
            field=models.BooleanField(default=False),
        ),
    ]
