# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-08 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0089_message_applicationmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableWeekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('weekday', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='availabilityType',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
