# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-18 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0091_availabledate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableDate',
            new_name='AvailabilityDate',
        ),
    ]
