# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-23 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgencyApp', '0093_availableweekday_repeatweeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableweekday',
            name='repeatWeeks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
